"""Shared test constants for the v0.2.0 test suites.

These values define the default test scenario and must remain consistent
with the existing v0.1.0 test fixtures for behavioral comparison.
"""

# Framework defaults
DEFAULT_SEED = 42
DEFAULT_MAX_STEPS = 200
DEFAULT_GRID_WIDTH = 10
DEFAULT_GRID_HEIGHT = 10
DEFAULT_OBSTACLE_DENSITY = 0.0

# System A defaults
DEFAULT_INITIAL_ENERGY = 50.0
DEFAULT_MAX_ENERGY = 100.0
DEFAULT_BUFFER_CAPACITY = 5
DEFAULT_TEMPERATURE = 1.0
DEFAULT_SELECTION_MODE = "sample"
DEFAULT_STAY_SUPPRESSION = 0.1
DEFAULT_CONSUME_WEIGHT = 1.5
DEFAULT_MOVE_COST = 1.0
DEFAULT_CONSUME_COST = 1.0
DEFAULT_STAY_COST = 0.5
DEFAULT_MAX_CONSUME = 1.0
DEFAULT_ENERGY_GAIN_FACTOR = 10.0

# System A+W defaults
DEFAULT_BASE_CURIOSITY = 1.0
DEFAULT_SPATIAL_SENSORY_BALANCE = 0.5
DEFAULT_EXPLORE_SUPPRESSION = 0.3
DEFAULT_HUNGER_WEIGHT_BASE = 0.3
DEFAULT_CURIOSITY_WEIGHT_BASE = 1.0
DEFAULT_GATING_SHARPNESS = 2.0

# System C defaults
DEFAULT_MEMORY_LEARNING_RATE = 0.3
DEFAULT_CONTEXT_THRESHOLD = 0.5
DEFAULT_FRUSTRATION_RATE = 0.2
DEFAULT_CONFIDENCE_RATE = 0.15
DEFAULT_POSITIVE_SENSITIVITY = 1.0
DEFAULT_NEGATIVE_SENSITIVITY = 1.5
DEFAULT_MODULATION_MIN = 0.3
DEFAULT_MODULATION_MAX = 2.0
DEFAULT_MODULATION_MODE = "multiplicative"
DEFAULT_PREDICTION_BIAS_SCALE = 0.2
DEFAULT_PREDICTION_BIAS_CLIP = 1.0
DEFAULT_POSITIVE_WEIGHTS = (0.5, 0.125, 0.125, 0.125, 0.125)
DEFAULT_NEGATIVE_WEIGHTS = (0.5, 0.125, 0.125, 0.125, 0.125)
